const lorem = `__Tom Sawyer__ is an orphan who lives with his aunt, Polly, and his half-brother, Sid, in the town of St. Petersburg, Missouri, which is based on __Hannibal__, Missouri, where __Mark Twain__ originally lived, sometime in the 1840s. A fun-loving boy, Tom skips school to go swimming and is made to whitewash his aunt's fence for the entirety of the next day, Saturday, as punishment.

In one of the most famous scenes in American literature, Tom cleverly persuades the several neighborhood children to trade him small trinkets and treasures for the "privilege" of doing his tedious work, using reverse psychology to convince them it is an enjoyable activity. Later, Tom trades the trinkets with other students for several denominations of tickets, obtained at the local Sunday school for memorizing verses of Scripture. Tom then exchanges the tickets with the minister for a prized Bible, despite being one of the worst students in the Sunday school and knowing almost nothing of Scripture, eliciting envy from the students and a mixture of pride and shock from the adults.

Tom falls in love with a girl named __Becky Thatcher__, who is new in town and the daughter of a prominent judge. Tom wins the admiration of the judge in the church by obtaining the Bible as a prize, but reveals his ignorance when he is unable to answer basic questions about Scripture. Tom pursues Becky, eventually persuading her to get engaged by kissing her. Their romance soon collapses when she discovers that Tom was engaged to another schoolgirl, Amy Lawrence.

Shortly after Becky shuns Tom, he accompanies __Huckleberry Finn__, a vagrant boy whom all the other boys admire, to a graveyard at midnight to perform a superstitious ritual designed to heal warts. At the graveyard, they witness a trio of body snatchers, Dr Robinson, __Muff Potter__ and Injun Joe, robbing a grave. Muff Potter is drunk and eventually blacks out, while Injun Joe gets into a fight with Dr Robinson and murders him. Injun Joe appears to frame Muff Potter for the murder. Tom and Huckleberry Finn swear a blood oath not to tell anyone about the murder, fearing Injun Joe would somehow discover it was them and murder them in turn. Muff Potter is eventually jailed, and he accepts the blame, assuming he committed the killing in an act of drunkenness.

Tom grows bored with school, and along with his friends Joe Harper and Huckleberry Finn, he runs away to Jackson's Island in the __Mississippi__ River to begin life as "pirates". While enjoying their freedom, they become aware that the community is scouring the river for their bodies, as the boys are missing and presumed dead. Tom sneaks back home one night to observe the commotion and after a brief moment of remorse at his loved ones' suffering, he is struck by the grand idea of appearing at his funeral. The trio later carries out this scheme, making a sensational and sudden appearance at church in the middle of their joint funeral service, winning the immense respect of their classmates for the stunt. Back in school, Becky has ripped the school master's anatomy book after Tom startles her, but Tom regains her admiration by nobly accepting the blame and punishment for tearing the book.

In court, __Injun Joe__ pins the murder on Muff Potter. Tom decides to defy his blood oath with Huck and testifies against Injun Joe, who quickly escapes through a window before he can be apprehended. The boys live in constant fear of Joe's revenge for incriminating him.

Summer arrives and Tom and Huck decide to hunt for buried treasure in a haunted house. After venturing upstairs, they hear a noise below and peering through holes in the floor, they see the deaf-mute Spaniard who had shown up in the village some weeks before revealing himself to be Injun Joe. Speaking freely, Injun Joe and a companion plan to bury some stolen treasure of their own in the house. From their hiding spot, Tom and Huck wriggle with delight at the prospect of digging it up. By chance, the villains discover an even greater gold hoard buried in the hearth and carry it off to a better hiding place. The boys are determined to find it and one night, Huck spots them and follows them; he overhears Injun Joe's plans to break into the house of the wealthy __Widow Douglas__ and mutilate her face in revenge for her late husband, a justice of the peace, having once ordered him to be publicly whipped for vagrancy. Running to fetch help, Huck prevents the crime and requests his name not be made public, for fear of Injun Joe's retaliation, thus becoming an anonymous hero.

Just before Huck stops the crime, Tom goes on a picnic to __McDougal's cave__ with Becky and their classmates. Tom and Becky get lost and wander in the cave for several days, facing starvation and dehydration. Becky becomes extremely dehydrated and weak, and Tom's search for a way out grows more desperate. He encounters Injun Joe in the caves one day but is not seen by his nemesis. Eventually, Tom finds a way out and they are joyfully welcomed back by their community. Becky's father, Judge Thatcher, has McDougal's cave sealed with an iron door. When Tom hears of the sealing two weeks later, he is horror-stricken, knowing that Injun Joe is still inside. He directs a posse to the cave, where they find Injun Joe's corpse just inside the sealed entrance, starved to death after having consumed raw bats and candle stubs as a last resort. The place of his death and the in situ cups he used to collect water from a dripping stalactite become a local tourist attraction.

A week later, having deduced from Injun Joe's presence at McDougal's cave that the villain must have hidden the stolen gold inside, Tom takes Huck to the cave and they find the box of gold, the proceeds of which are invested for them. The Widow Douglas adopts Huck, but he finds the restrictions of a civilized home life painful, attempting to escape back to his vagrant life. Tom convinces Huck to go back to the widow so that he can later be a robber with Tom, because you need to be high society to be in a robber gang. Reluctantly, Huck agrees and goes back to the widow.`
export default lorem
